# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podujatie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapa', models.CharField(default=None, max_length=50)),
                ('typ', models.CharField(choices=[(0, 'Hlavna'), (1, 'Vedlajsia')], max_length=1)),
                ('lavy_horny_roh_gps_latitude', models.FloatField(default=None)),
                ('lavy_horny_roh_gps_longitude', models.FloatField(default=None)),
                ('pravy_spodny_roh_gps_latitude', models.FloatField(default=None)),
                ('pravy_spodny_roh_gps_longitude', models.FloatField(default=None)),
                ('podujatie_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='podujatie.Podujatie')),
            ],
        ),
    ]
