# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapa',
            name='mapa',
            field=models.ImageField(default=None, upload_to=b''),
        ),
    ]
