# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_auto_20160214_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapa',
            options={'verbose_name_plural': 'Mapy'},
        ),
    ]
