# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zaner', '0001_initial'),
        ('podujatie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZanerPodujatia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podujatie_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='podujatie.Podujatie')),
                ('zaner_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='zaner.Zaner')),
            ],
        ),
    ]
