# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(default=None, max_length=255)),
                ('foto', models.ImageField(null=True, upload_to=b'')),
            ],
            options={
                'verbose_name_plural': 'Skupiny',
            },
        ),
    ]
