# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zaner',
            options={'verbose_name_plural': 'Zanre'},
        ),
    ]
