# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tovar', '0001_initial'),
        ('stanok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarStanku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=10000, null=True)),
                ('cena', models.FloatField(default=None)),
                ('stanok_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stanok.Stanok')),
                ('tovar_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tovar.Tovar')),
            ],
            options={
                'verbose_name_plural': 'Tovar Stankov',
            },
        ),
    ]
