# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapa', '0003_auto_20160214_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(default=None, max_length=255)),
                ('lavy_horny_roh_x', models.FloatField(default=None)),
                ('lavy_horny_roh_y', models.FloatField(default=None)),
                ('pravy_spodny_roh_x', models.FloatField(default=None)),
                ('pravy_spodny_roh_y', models.FloatField(default=None)),
                ('mapa_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mapa.Mapa')),
            ],
            options={
                'verbose_name_plural': 'Stanky',
            },
        ),
    ]
