# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podujatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(default=None, max_length=50)),
                ('typ', models.CharField(choices=[(0, 'Festival'), (1, 'Hody')], max_length=1)),
                ('datum_od', models.DateField(default=None)),
                ('datum_do', models.DateField(default=None)),
                ('administrator_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
