# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podium', '0001_initial'),
        ('skupina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkupinaPodia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=10000, null=True)),
                ('cas_od', models.DateTimeField(default=None)),
                ('cas_do', models.DateTimeField(default=None)),
                ('podium_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='podium.Podium')),
                ('skupina_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='skupina.Skupina')),
            ],
            options={
                'verbose_name_plural': 'Skupiny podia',
            },
        ),
    ]
